---
commands:
  - type: execute
    host: netcup
    username: mp
    ssh_key: true
    command: ls -l > /tmp/data
  - type: sftp_get
    host: netcup
    username: mp
    ssh_key: true
    src_file: /tmp/data
    dst_file: /tmp/cockpit/data_1
result:
  - key: data1
    file: /tmp/cockpit/data_1
