services:
  cockpit-ng:
    build:
      context: ..
      dockerfile: docker/Dockerfile.basic
    container_name: cockpit-ng
    ports:
      - "3000:3000"  # Frontend (Next.js)
      - "8000:8000"  # Backend (FastAPI)
    environment:
      # Backend Environment Variables
      - NAUTOBOT_URL=${NAUTOBOT_URL:-http://localhost:8080}
      - NAUTOBOT_TOKEN=${NAUTOBOT_TOKEN:-your_nautobot_token_here}
      - NAUTOBOT_TIMEOUT=${NAUTOBOT_TIMEOUT:-30}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-this-in-production}
      - DATA_DIR=/app/data
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
      # Frontend Environment Variables
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      # Persist data directory
      - cockpit_data:/app/data
      # Optional: Mount external configuration
      - ./config:/app/config:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health", "||", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cockpit-network

volumes:
  cockpit_data:
    driver: local

networks:
  cockpit-network:
    driver: bridge
